BEGIN;

ALTER TABLE championships
ADD COLUMN IF NOT EXISTS competition_format VARCHAR(80),
ADD COLUMN IF NOT EXISTS end_date DATE,
ADD COLUMN IF NOT EXISTS registration_deadline DATE,
ADD COLUMN IF NOT EXISTS registrations_open BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN IF NOT EXISTS address VARCHAR(255),
ADD COLUMN IF NOT EXISTS neighborhood VARCHAR(120),
ADD COLUMN IF NOT EXISTS state VARCHAR(2),
ADD COLUMN IF NOT EXISTS zip_code VARCHAR(12),
ADD COLUMN IF NOT EXISTS reference_point VARCHAR(180),
ADD COLUMN IF NOT EXISTS court_or_field VARCHAR(120),
ADD COLUMN IF NOT EXISTS rules TEXT,
ADD COLUMN IF NOT EXISTS tiebreak_rules TEXT,
ADD COLUMN IF NOT EXISTS qualification_rules TEXT,
ADD COLUMN IF NOT EXISTS elimination_rules TEXT,
ADD COLUMN IF NOT EXISTS required_documents TEXT,
ADD COLUMN IF NOT EXISTS cancellation_policy TEXT;

CREATE TABLE IF NOT EXISTS teams (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    championship_id BIGINT NOT NULL,
    name VARCHAR(140) NOT NULL,
    shield VARCHAR(255),
    city VARCHAR(100),
    responsible_name VARCHAR(120),
    responsible_phone VARCHAR(30),
    status VARCHAR(20) NOT NULL DEFAULT 'pendente',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_teams_championship FOREIGN KEY (championship_id) REFERENCES championships(id) ON DELETE CASCADE,
    CONSTRAINT chk_teams_status CHECK (status IN ('pendente', 'aprovado', 'rejeitado', 'cancelado'))
);

CREATE TABLE IF NOT EXISTS athletes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    team_id BIGINT,
    championship_id BIGINT NOT NULL,
    name VARCHAR(120) NOT NULL,
    photo VARCHAR(255),
    birth_date DATE,
    city VARCHAR(100),
    shirt_number INTEGER,
    position VARCHAR(80),
    category VARCHAR(100),
    status VARCHAR(20) NOT NULL DEFAULT 'pendente',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_athletes_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_athletes_team FOREIGN KEY (team_id) REFERENCES teams(id) ON DELETE SET NULL,
    CONSTRAINT fk_athletes_championship FOREIGN KEY (championship_id) REFERENCES championships(id) ON DELETE CASCADE,
    CONSTRAINT chk_athletes_status CHECK (status IN ('pendente', 'aprovado', 'rejeitado', 'cancelado'))
);

CREATE TABLE IF NOT EXISTS matches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    championship_id BIGINT NOT NULL,
    phase VARCHAR(80) NOT NULL DEFAULT 'fase unica',
    group_name VARCHAR(80),
    round_number INTEGER,
    home_team_id BIGINT,
    away_team_id BIGINT,
    home_athlete_id BIGINT,
    away_athlete_id BIGINT,
    match_date DATE,
    match_time TIME,
    venue VARCHAR(180),
    court_or_field VARCHAR(120),
    referee VARCHAR(120),
    home_score INTEGER,
    away_score INTEGER,
    status VARCHAR(20) NOT NULL DEFAULT 'agendada',
    next_match_id BIGINT,
    next_match_position VARCHAR(10),
    winner_team_id BIGINT,
    winner_athlete_id BIGINT,
    notes TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_matches_championship FOREIGN KEY (championship_id) REFERENCES championships(id) ON DELETE CASCADE,
    CONSTRAINT fk_matches_home_team FOREIGN KEY (home_team_id) REFERENCES teams(id) ON DELETE SET NULL,
    CONSTRAINT fk_matches_away_team FOREIGN KEY (away_team_id) REFERENCES teams(id) ON DELETE SET NULL,
    CONSTRAINT fk_matches_home_athlete FOREIGN KEY (home_athlete_id) REFERENCES athletes(id) ON DELETE SET NULL,
    CONSTRAINT fk_matches_away_athlete FOREIGN KEY (away_athlete_id) REFERENCES athletes(id) ON DELETE SET NULL,
    CONSTRAINT fk_matches_next_match FOREIGN KEY (next_match_id) REFERENCES matches(id) ON DELETE SET NULL,
    CONSTRAINT fk_matches_winner_team FOREIGN KEY (winner_team_id) REFERENCES teams(id) ON DELETE SET NULL,
    CONSTRAINT fk_matches_winner_athlete FOREIGN KEY (winner_athlete_id) REFERENCES athletes(id) ON DELETE SET NULL,
    CONSTRAINT chk_matches_status CHECK (status IN ('agendada', 'em_andamento', 'finalizada', 'adiada', 'cancelada')),
    CONSTRAINT chk_matches_next_position CHECK (next_match_position IS NULL OR next_match_position IN ('home', 'away'))
);

CREATE TABLE IF NOT EXISTS match_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    match_id BIGINT NOT NULL,
    team_id BIGINT,
    athlete_id BIGINT,
    event_type VARCHAR(40) NOT NULL,
    minute INTEGER,
    additional_time INTEGER,
    value INTEGER,
    description TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_match_events_match FOREIGN KEY (match_id) REFERENCES matches(id) ON DELETE CASCADE,
    CONSTRAINT fk_match_events_team FOREIGN KEY (team_id) REFERENCES teams(id) ON DELETE SET NULL,
    CONSTRAINT fk_match_events_athlete FOREIGN KEY (athlete_id) REFERENCES athletes(id) ON DELETE SET NULL,
    CONSTRAINT chk_match_events_type CHECK (event_type IN ('gol', 'gol_contra', 'penalti_convertido', 'penalti_perdido', 'cartao_amarelo', 'cartao_vermelho', 'substituicao', 'ponto', 'saque', 'bloqueio', 'observacao'))
);

CREATE TABLE IF NOT EXISTS match_sets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    match_id BIGINT NOT NULL,
    set_number INTEGER NOT NULL,
    home_score INTEGER NOT NULL DEFAULT 0,
    away_score INTEGER NOT NULL DEFAULT 0,
    winner_team_id BIGINT,
    winner_athlete_id BIGINT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_match_sets_match FOREIGN KEY (match_id) REFERENCES matches(id) ON DELETE CASCADE,
    CONSTRAINT fk_match_sets_winner_team FOREIGN KEY (winner_team_id) REFERENCES teams(id) ON DELETE SET NULL,
    CONSTRAINT fk_match_sets_winner_athlete FOREIGN KEY (winner_athlete_id) REFERENCES athletes(id) ON DELETE SET NULL,
    CONSTRAINT unique_match_set UNIQUE (match_id, set_number)
);

CREATE TABLE IF NOT EXISTS standings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    championship_id BIGINT NOT NULL,
    team_id BIGINT,
    athlete_id BIGINT,
    group_name VARCHAR(80),
    played INTEGER NOT NULL DEFAULT 0,
    wins INTEGER NOT NULL DEFAULT 0,
    draws INTEGER NOT NULL DEFAULT 0,
    losses INTEGER NOT NULL DEFAULT 0,
    score_for INTEGER NOT NULL DEFAULT 0,
    score_against INTEGER NOT NULL DEFAULT 0,
    score_difference INTEGER NOT NULL DEFAULT 0,
    points INTEGER NOT NULL DEFAULT 0,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_standings_championship FOREIGN KEY (championship_id) REFERENCES championships(id) ON DELETE CASCADE,
    CONSTRAINT fk_standings_team FOREIGN KEY (team_id) REFERENCES teams(id) ON DELETE CASCADE,
    CONSTRAINT fk_standings_athlete FOREIGN KEY (athlete_id) REFERENCES athletes(id) ON DELETE CASCADE,
    CONSTRAINT unique_standing_team UNIQUE (championship_id, team_id, group_name),
    CONSTRAINT unique_standing_athlete UNIQUE (championship_id, athlete_id, group_name)
);

CREATE TABLE IF NOT EXISTS athlete_statistics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    championship_id BIGINT NOT NULL,
    athlete_id BIGINT NOT NULL,
    team_id BIGINT,
    matches_played INTEGER NOT NULL DEFAULT 0,
    goals INTEGER NOT NULL DEFAULT 0,
    assists INTEGER NOT NULL DEFAULT 0,
    yellow_cards INTEGER NOT NULL DEFAULT 0,
    red_cards INTEGER NOT NULL DEFAULT 0,
    points INTEGER NOT NULL DEFAULT 0,
    aces INTEGER NOT NULL DEFAULT 0,
    blocks INTEGER NOT NULL DEFAULT 0,
    sets_won INTEGER NOT NULL DEFAULT 0,
    sets_lost INTEGER NOT NULL DEFAULT 0,
    wins INTEGER NOT NULL DEFAULT 0,
    losses INTEGER NOT NULL DEFAULT 0,
    final_time VARCHAR(40),
    position_number INTEGER,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_athlete_statistics_championship FOREIGN KEY (championship_id) REFERENCES championships(id) ON DELETE CASCADE,
    CONSTRAINT fk_athlete_statistics_athlete FOREIGN KEY (athlete_id) REFERENCES athletes(id) ON DELETE CASCADE,
    CONSTRAINT fk_athlete_statistics_team FOREIGN KEY (team_id) REFERENCES teams(id) ON DELETE SET NULL,
    CONSTRAINT unique_athlete_statistics UNIQUE (championship_id, athlete_id)
);

CREATE INDEX IF NOT EXISTS idx_teams_championship ON teams (championship_id);
CREATE INDEX IF NOT EXISTS idx_athletes_championship ON athletes (championship_id);
CREATE INDEX IF NOT EXISTS idx_athletes_team ON athletes (team_id);
CREATE INDEX IF NOT EXISTS idx_matches_championship ON matches (championship_id);
CREATE INDEX IF NOT EXISTS idx_matches_schedule ON matches (championship_id, phase, round_number, match_date, match_time);
CREATE INDEX IF NOT EXISTS idx_match_events_match ON match_events (match_id);
CREATE INDEX IF NOT EXISTS idx_match_sets_match ON match_sets (match_id);
CREATE INDEX IF NOT EXISTS idx_standings_championship ON standings (championship_id, group_name, points DESC);
CREATE INDEX IF NOT EXISTS idx_athlete_statistics_championship ON athlete_statistics (championship_id, goals DESC);

COMMIT;
