BEGIN;

CREATE TABLE IF NOT EXISTS organizer_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    responsible_name VARCHAR(160) NOT NULL,
    document_number VARCHAR(32) NOT NULL,
    organization_name VARCHAR(160) NOT NULL,
    organization_type VARCHAR(80) NOT NULL,
    phone VARCHAR(30) NOT NULL,
    city VARCHAR(100) NOT NULL,
    state VARCHAR(2) NOT NULL,
    description TEXT NOT NULL,
    proof_file VARCHAR(255),
    status VARCHAR(20) NOT NULL DEFAULT 'pending',
    approved_by BIGINT,
    approved_at TIMESTAMP,
    rejection_reason TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_organizer_requests_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

ALTER TABLE organizer_requests
ADD COLUMN IF NOT EXISTS approved_by BIGINT,
ADD COLUMN IF NOT EXISTS approved_at TIMESTAMP,
ADD COLUMN IF NOT EXISTS rejection_reason TEXT,
ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_name = 'organizer_requests'
          AND column_name = 'reviewed_by'
    ) THEN
        EXECUTE 'UPDATE organizer_requests
                 SET approved_by = COALESCE(approved_by, reviewed_by)
                 WHERE status = ''approved'' AND approved_by IS NULL';
    END IF;

    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_name = 'organizer_requests'
          AND column_name = 'reviewed_at'
    ) THEN
        EXECUTE 'UPDATE organizer_requests
                 SET approved_at = COALESCE(approved_at, reviewed_at)
                 WHERE status = ''approved'' AND approved_at IS NULL';
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'fk_organizer_requests_approved_by'
    ) THEN
        ALTER TABLE organizer_requests
        ADD CONSTRAINT fk_organizer_requests_approved_by
        FOREIGN KEY (approved_by) REFERENCES users(id) ON DELETE SET NULL;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'chk_organizer_requests_status_final'
    ) THEN
        ALTER TABLE organizer_requests
        ADD CONSTRAINT chk_organizer_requests_status_final
        CHECK (status IN ('pending', 'approved', 'rejected')) NOT VALID;
    END IF;
END $$;

CREATE UNIQUE INDEX IF NOT EXISTS idx_organizer_requests_one_pending_per_user
ON organizer_requests (user_id)
WHERE status = 'pending';

CREATE INDEX IF NOT EXISTS idx_organizer_requests_pending_created
ON organizer_requests (status, created_at DESC);

COMMIT;
