BEGIN;

CREATE TABLE IF NOT EXISTS competition_activity_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    championship_id BIGINT NOT NULL,
    user_id BIGINT,
    action VARCHAR(80) NOT NULL,
    description TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_competition_logs_championship FOREIGN KEY (championship_id) REFERENCES championships(id) ON DELETE CASCADE,
    CONSTRAINT fk_competition_logs_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_competition_logs_championship ON competition_activity_logs (championship_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_competition_logs_user ON competition_activity_logs (user_id);
CREATE INDEX IF NOT EXISTS idx_match_events_type ON match_events (event_type);
CREATE INDEX IF NOT EXISTS idx_matches_status ON matches (championship_id, status);

COMMIT;
