BEGIN;

ALTER TABLE users
ADD COLUMN IF NOT EXISTS suspended_at TIMESTAMP,
ADD COLUMN IF NOT EXISTS suspension_reason TEXT,
ADD COLUMN IF NOT EXISTS is_demo BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE championships
ADD COLUMN IF NOT EXISTS editorial_status VARCHAR(30) NOT NULL DEFAULT 'draft',
ADD COLUMN IF NOT EXISTS publication_requested_at TIMESTAMP,
ADD COLUMN IF NOT EXISTS published_at TIMESTAMP,
ADD COLUMN IF NOT EXISTS reviewed_by BIGINT,
ADD COLUMN IF NOT EXISTS reviewed_at TIMESTAMP,
ADD COLUMN IF NOT EXISTS rejection_reason TEXT,
ADD COLUMN IF NOT EXISTS registration_type VARCHAR(20) NOT NULL DEFAULT 'individual',
ADD COLUMN IF NOT EXISTS maximum_registrations INTEGER,
ADD COLUMN IF NOT EXISTS minimum_team_members INTEGER,
ADD COLUMN IF NOT EXISTS maximum_team_members INTEGER,
ADD COLUMN IF NOT EXISTS requires_documents BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS requires_payment BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS pix_key VARCHAR(120),
ADD COLUMN IF NOT EXISTS payment_instructions TEXT,
ADD COLUMN IF NOT EXISTS latitude NUMERIC(10,7),
ADD COLUMN IF NOT EXISTS longitude NUMERIC(10,7),
ADD COLUMN IF NOT EXISTS is_demo BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE registrations
ADD COLUMN IF NOT EXISTS registration_type VARCHAR(20) NOT NULL DEFAULT 'individual',
ADD COLUMN IF NOT EXISTS team_id BIGINT,
ADD COLUMN IF NOT EXISTS rejection_reason TEXT,
ADD COLUMN IF NOT EXISTS internal_notes TEXT,
ADD COLUMN IF NOT EXISTS accepted_terms BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS terms_version VARCHAR(40),
ADD COLUMN IF NOT EXISTS accepted_terms_at TIMESTAMP,
ADD COLUMN IF NOT EXISTS accepted_terms_ip VARCHAR(45),
ADD COLUMN IF NOT EXISTS is_demo BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE teams ADD COLUMN IF NOT EXISTS is_demo BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE athletes ADD COLUMN IF NOT EXISTS is_demo BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE matches ADD COLUMN IF NOT EXISTS is_rescheduled BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE matches ADD COLUMN IF NOT EXISTS is_demo BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE notifications
ADD COLUMN IF NOT EXISTS title VARCHAR(160),
ADD COLUMN IF NOT EXISTS link VARCHAR(255),
ADD COLUMN IF NOT EXISTS type VARCHAR(60) NOT NULL DEFAULT 'info',
ADD COLUMN IF NOT EXISTS is_read BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE competition_activity_logs
ADD COLUMN IF NOT EXISTS entity_type VARCHAR(80),
ADD COLUMN IF NOT EXISTS entity_id BIGINT,
ADD COLUMN IF NOT EXISTS old_value TEXT,
ADD COLUMN IF NOT EXISTS new_value TEXT,
ADD COLUMN IF NOT EXISTS ip_address VARCHAR(45);

CREATE TABLE IF NOT EXISTS organizer_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    responsible_name VARCHAR(160) NOT NULL,
    document_number VARCHAR(32) NOT NULL,
    organization_name VARCHAR(160) NOT NULL,
    organization_type VARCHAR(80) NOT NULL,
    phone VARCHAR(30) NOT NULL,
    city VARCHAR(100) NOT NULL,
    state VARCHAR(2) NOT NULL,
    description TEXT NOT NULL,
    proof_file VARCHAR(255),
    status VARCHAR(20) NOT NULL DEFAULT 'pending',
    rejection_reason TEXT,
    reviewed_by BIGINT,
    reviewed_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_organizer_requests_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_organizer_requests_reviewer FOREIGN KEY (reviewed_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT chk_organizer_requests_status CHECK (status IN ('pending', 'approved', 'rejected', 'suspended'))
);

CREATE TABLE IF NOT EXISTS registration_documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    registration_id BIGINT NOT NULL,
    document_type VARCHAR(40) NOT NULL,
    original_name VARCHAR(255) NOT NULL,
    stored_name VARCHAR(255) NOT NULL,
    file_path VARCHAR(255) NOT NULL,
    mime_type VARCHAR(120) NOT NULL,
    file_size BIGINT NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'under_review',
    rejection_reason TEXT,
    reviewed_by BIGINT,
    reviewed_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_registration_documents_registration FOREIGN KEY (registration_id) REFERENCES registrations(id) ON DELETE CASCADE,
    CONSTRAINT fk_registration_documents_reviewer FOREIGN KEY (reviewed_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT chk_registration_documents_type CHECK (document_type IN ('identity_document','medical_certificate','parental_authorization','team_roster','payment_receipt','responsibility_term','other')),
    CONSTRAINT chk_registration_documents_status CHECK (status IN ('pending','under_review','approved','rejected'))
);

CREATE TABLE IF NOT EXISTS registration_payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    registration_id BIGINT NOT NULL,
    payment_method VARCHAR(30) NOT NULL DEFAULT 'free',
    amount NUMERIC(10,2) NOT NULL DEFAULT 0,
    pix_key VARCHAR(120),
    receipt_file VARCHAR(255),
    status VARCHAR(30) NOT NULL DEFAULT 'pending',
    reviewed_by BIGINT,
    reviewed_at TIMESTAMP,
    rejection_reason TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_registration_payments_registration FOREIGN KEY (registration_id) REFERENCES registrations(id) ON DELETE CASCADE,
    CONSTRAINT fk_registration_payments_reviewer FOREIGN KEY (reviewed_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT chk_registration_payments_method CHECK (payment_method IN ('pix','cash','bank_transfer','free')),
    CONSTRAINT chk_registration_payments_status CHECK (status IN ('pending','awaiting_receipt','under_review','paid','rejected','refunded','waived'))
);

CREATE TABLE IF NOT EXISTS match_reschedules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    match_id BIGINT NOT NULL,
    changed_by BIGINT,
    old_date DATE,
    old_time TIME,
    old_venue VARCHAR(180),
    new_date DATE,
    new_time TIME,
    new_venue VARCHAR(180),
    reason TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_match_reschedules_match FOREIGN KEY (match_id) REFERENCES matches(id) ON DELETE CASCADE,
    CONSTRAINT fk_match_reschedules_user FOREIGN KEY (changed_by) REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS match_lineups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    match_id BIGINT NOT NULL,
    team_id BIGINT,
    athlete_id BIGINT NOT NULL,
    is_starter BOOLEAN NOT NULL DEFAULT false,
    is_captain BOOLEAN NOT NULL DEFAULT false,
    shirt_number INTEGER,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_match_lineups_match FOREIGN KEY (match_id) REFERENCES matches(id) ON DELETE CASCADE,
    CONSTRAINT fk_match_lineups_team FOREIGN KEY (team_id) REFERENCES teams(id) ON DELETE SET NULL,
    CONSTRAINT fk_match_lineups_athlete FOREIGN KEY (athlete_id) REFERENCES athletes(id) ON DELETE CASCADE,
    CONSTRAINT unique_match_lineup_athlete UNIQUE (match_id, athlete_id)
);

CREATE TABLE IF NOT EXISTS match_reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    match_id BIGINT NOT NULL UNIQUE,
    referee_name VARCHAR(120),
    summary TEXT,
    incidents TEXT,
    organizer_confirmation BOOLEAN NOT NULL DEFAULT false,
    home_team_confirmation BOOLEAN NOT NULL DEFAULT false,
    away_team_confirmation BOOLEAN NOT NULL DEFAULT false,
    finalized_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_match_reports_match FOREIGN KEY (match_id) REFERENCES matches(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reporter_user_id BIGINT NOT NULL,
    championship_id BIGINT,
    reported_user_id BIGINT,
    report_type VARCHAR(40) NOT NULL,
    title VARCHAR(160) NOT NULL,
    description TEXT NOT NULL,
    evidence_file VARCHAR(255),
    status VARCHAR(30) NOT NULL DEFAULT 'open',
    admin_notes TEXT,
    reviewed_by BIGINT,
    reviewed_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_reports_reporter FOREIGN KEY (reporter_user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_reports_championship FOREIGN KEY (championship_id) REFERENCES championships(id) ON DELETE CASCADE,
    CONSTRAINT fk_reports_user FOREIGN KEY (reported_user_id) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_reports_reviewer FOREIGN KEY (reviewed_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT chk_reports_type CHECK (report_type IN ('fake_championship','incorrect_information','improper_charge','offensive_behavior','incorrect_result','fraud','other')),
    CONSTRAINT chk_reports_status CHECK (status IN ('open','under_review','resolved','rejected','archived'))
);

CREATE INDEX IF NOT EXISTS idx_organizer_requests_status ON organizer_requests (status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_championships_editorial_status ON championships (editorial_status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_registration_documents_status ON registration_documents (status);
CREATE INDEX IF NOT EXISTS idx_registration_payments_status ON registration_payments (status);
CREATE INDEX IF NOT EXISTS idx_match_reschedules_match ON match_reschedules (match_id);
CREATE INDEX IF NOT EXISTS idx_reports_status ON reports (status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_notifications_unread ON notifications (user_id, is_read, created_at DESC);

COMMIT;
